### ISSUE TITLE
name 'AtomicInt' is not defined, doesn't work at all

### ISSUE THREAD

**Issue by Jiajun-Fan** [aliyun/aliyun-cli#10]
Doesn't work at all. 

```
$ aliyuncli --help
Traceback (most recent call last):
  File "/usr/local/bin/aliyuncli", line 9, in <module>
    load_entry_point('aliyuncli==2.1.2', 'console_scripts', 'aliyuncli')()
  File "/Library/Python/2.7/site-packages/setuptools-3.4.4-py2.7.egg/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Python/2.7/site-packages/setuptools-3.4.4-py2.7.egg/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/Library/Python/2.7/site-packages/setuptools-3.4.4-py2.7.egg/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/aliyuncli/aliyuncli.py", line 25, in <module>
    import aliyunCliMain
  File "/Library/Python/2.7/site-packages/aliyuncli/aliyunCliMain.py", line 21, in <module>
    import aliyunOpenApiData
  File "/Library/Python/2.7/site-packages/aliyuncli/aliyunOpenApiData.py", line 22, in <module>
    import aliyunExtensionCliHandler
  File "/Library/Python/2.7/site-packages/aliyuncli/aliyunExtensionCliHandler.py", line 24, in <module>
    import advance.userProfileHandler
  File "/Library/Python/2.7/site-packages/aliyuncli/advance/userProfileHandler.py", line 5, in <module>
    import aliyunExtensionCliHandler
  File "/Library/Python/2.7/site-packages/aliyuncli/aliyunExtensionCliHandler.py", line 22, in <module>
    import aliyunCliHelp
  File "/Library/Python/2.7/site-packages/aliyuncli/aliyunCliHelp.py", line 20, in <module>
    import aliyunOpenApiData
  File "/Library/Python/2.7/site-packages/aliyuncli/aliyunOpenApiData.py", line 48, in <module>
    import ossadp.ossHandler
  File "/Library/Python/2.7/site-packages/aliyuncli/ossadp/ossHandler.py", line 44, in <module>
    TOTAL_PUT = AtomicInt()
NameError: name 'AtomicInt' is not defined
```

**Comment by xning** [comment]
I have tried the new version installed by the _pip_ command and the issue is fixed. @Jiajun-Fan pls install the new version and try it. Thanks.

**Comment by Jiajun-Fan** [comment]
I noted this crash happens on OSX platform. I successfully ran aliyuncli on a ubuntu machine, but still got this crash even after upgrading aliyuncli or reinstalling it.

The crash happens when import ossadp.ossHandler, there is an undefined class "AtomicInt", as long as ossHandler is imported, the crash happens.

On Ubuntu platform, it throw an exception "No module named oss.oss_api", so it enters line 45 and doesn't import ossadp.ossHandler, and alliyuncli works fine.
On OSX platform, oss_api is successfully imported and it enters line 48 then it crashss.

In file aliyuncli/aliyunOpenApiData.py Line 48.
 40 try:
 41     import oss.oss_api
 42     import oss.oss_util
 43     import oss.oss_xml_handler
 44 except Exception:
 45     pass
 46 else:
 47     nonStandardSdkCmds.append('oss')
 48     import ossadp.ossHandler

I don't know the logic this try-except block, anyway why using a class "AtomicInt" which never defined?

**Comment by lvscar** [comment]
We have released a new command line tool for OSS operation. Please access https://github.com/aliyun/ossutil for the OSS CLI tool.

The latest version of aliyuncli will display advice for switching to the tool when OSS operation sub-command is typed.
