### ISSUE TITLE
NameError: name 'AtomicInt' is not defined

### ISSUE THREAD

**Issue by chilukey** [aliyun/aliyun-cli#24]
I am using CentOS 6.6, Python 2.6.6 and latest aliyuncli, the following error occurs when I use any aliyuncli command:
[root@56f20fb23c74 /]# aliyuncli configure
Traceback (most recent call last):
  File "/usr/bin/aliyuncli", line 7, in <module>
    from aliyuncli.aliyuncli import main
  File "/usr/lib/python2.6/site-packages/aliyuncli/aliyuncli.py", line 25, in <module>
    import aliyunCliMain
  File "/usr/lib/python2.6/site-packages/aliyuncli/aliyunCliMain.py", line 21, in <module>
    import aliyunOpenApiData
  File "/usr/lib/python2.6/site-packages/aliyuncli/aliyunOpenApiData.py", line 22, in <module>
    import aliyunExtensionCliHandler
  File "/usr/lib/python2.6/site-packages/aliyuncli/aliyunExtensionCliHandler.py", line 24, in <module>
    import advance.userProfileHandler
  File "/usr/lib/python2.6/site-packages/aliyuncli/advance/userProfileHandler.py", line 5, in <module>
    import aliyunExtensionCliHandler
  File "/usr/lib/python2.6/site-packages/aliyuncli/aliyunExtensionCliHandler.py", line 22, in <module>
    import aliyunCliHelp
  File "/usr/lib/python2.6/site-packages/aliyuncli/aliyunCliHelp.py", line 20, in <module>
    import aliyunOpenApiData
  File "/usr/lib/python2.6/site-packages/aliyuncli/aliyunOpenApiData.py", line 47, in <module>
    import ossadp.ossHandler
  File "/usr/lib/python2.6/site-packages/aliyuncli/ossadp/ossHandler.py", line 44, in <module>
    TOTAL_PUT = AtomicInt()
NameError: name 'AtomicInt' is not defined

**Comment by lvscar** [comment]
We have released a new command line tool for OSS operation.  Please access https://github.com/aliyun/ossutil for the OSS CLI tool.  
The latest version of aliyuncli will display advice for switching to the tool when OSS operation sub-command is typed.
