### ISSUE TITLE
release 3.0.41 test regression openapi

### ISSUE THREAD

**Issue by anthraxx** [aliyun/aliyun-cli#279]
Hi,

during build of the 3.0.41 release tag I get test failures related to openapi:

``
panic: read json from products.json failed &{[]} [recovered]
	panic: read json from products.json failed &{[]}
``

Previously I was able to successfully run `go test`

```
ok  	github.com/aliyun/aliyun-cli/cli	0.022s
ok  	github.com/aliyun/aliyun-cli/command	0.011s
ok  	github.com/aliyun/aliyun-cli/config	63.576s
ok  	github.com/aliyun/aliyun-cli/i18n	0.010s
?   	github.com/aliyun/aliyun-cli/main	[no test files]
--- FAIL: Test_main (0.00s)
panic: read json from products.json failed &{[]} [recovered]
	panic: read json from products.json failed &{[]}

goroutine 6 [running]:
testing.tRunner.func1.1(0x55bab7065f20, 0xc0003151f0)
	testing/testing.go:940 +0x2f7
testing.tRunner.func1(0xc00019b680)
	testing/testing.go:943 +0x3fb
panic(0x55bab7065f20, 0xc0003151f0)
	runtime/panic.go:969 +0x16a
github.com/aliyun/aliyun-cli/meta.LoadRepository(0x55bab7126fc0, 0x55bab777c220, 0x55bab66d109a)
	github.com/aliyun/aliyun-cli/meta/repository.go:35 +0x613
github.com/aliyun/aliyun-cli/openapi.NewLibrary(...)
	github.com/aliyun/aliyun-cli/openapi/library.go:38
github.com/aliyun/aliyun-cli/openapi.NewCommando(0x55bab7126a60, 0xc000317e30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/aliyun/aliyun-cli/openapi/commando.go:45 +0xa4
github.com/aliyun/aliyun-cli/openapi.Test_main(0xc00019b680)
	github.com/aliyun/aliyun-cli/openapi/commando_test.go:37 +0x1cb
testing.tRunner(0xc00019b680, 0x55bab70ef418)
	testing/testing.go:991 +0xde
created by testing.(*T).Run
	testing/testing.go:1042 +0x359
FAIL	github.com/aliyun/aliyun-cli/openapi	0.024s
?   	github.com/aliyun/aliyun-cli/resource	[no test files]
FAIL

```

**Comment by night556** [comment]
This may be because we changed the version of go-bindata, we changed from `https: // github.com / shuLhan / go-bindata` to` https: // github.com / jteeuwen / go-bindata`. And the packaging command has been changed to `go-bindata -o resource / metas.go -pkg resource ../ aliyun-openapi-meta / ...`

**Comment by anthraxx** [comment]
oh, thats totally awesome :heart_eyes_cat: 
PS: i'm sure you mean you changed from jteeuwen to shuLhan :wink: 

I guess you can close #262 as well with this nice change. Package now built successfully
