### ISSUE TITLE
error on cli commands from 3.0.74 to latest version 3.0.77

### ISSUE THREAD

**Issue by eclipseo** [aliyun/aliyun-cli#350]
* **Command Format**:
aliyun version

* **Execution Command**:
aliyun version

* **Output**:
```
panic: read json from products.json failed &{[]}

goroutine 1 [running]:
panic(0x55e335cb5b20, 0xc00040e650)
        /usr/lib/golang/src/runtime/panic.go:1065 +0x565 fp=0xc000195960 sp=0xc000195898 pc=0x55e334c8a7c5
github.com/aliyun/aliyun-cli/meta.LoadRepository(0x55e335d99dd8, 0x55e33651ab00, 0xc00040a9c0)
        /builddir/build/BUILD/aliyun-openapi-meta-92af720880941fb06015c8627ef6004def4e9de3/_build/src/github.com/aliyun/aliyun-cli/meta/repository.go:35 +0x625 fp=0xc000195ab0 sp=0xc000195960 pc=0x55e334fcbcc5
github.com/aliyun/aliyun-cli/openapi.NewLibrary(...)
        /builddir/build/BUILD/aliyun-openapi-meta-92af720880941fb06015c8627ef6004def4e9de3/_build/src/github.com/aliyun/aliyun-cli/openapi/library.go:38
github.com/aliyun/aliyun-cli/openapi.NewCommando(0x55e335d9ab98, 0xc000010018, 0x55e3356df3e4, 0x7, 0x55e3356dd0b5, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        /builddir/build/BUILD/aliyun-openapi-meta-92af720880941fb06015c8627ef6004def4e9de3/_build/src/github.com/aliyun/aliyun-cli/openapi/commando.go:45 +0xa9 fp=0xc000195af8 sp=0xc000195ab0 pc=0x55e33559cac9
main.main()
        /builddir/build/BUILD/aliyun-openapi-meta-92af720880941fb06015c8627ef6004def4e9de3/_build/src/github.com/aliyun/aliyun-cli/main/main.go:77 +0x478 fp=0xc000195f88 sp=0xc000195af8 pc=0x55e3356dbf58
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:225 +0x263 fp=0xc000195fe0 sp=0xc000195f88 pc=0x55e334c8d443
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000195fe8 sp=0xc000195fe0 pc=0x55e334cc0621

goroutine 2 [force gc (idle)]:
runtime.gopark(0x55e335d5b260, 0x55e3364eb930, 0x1411, 0x1)
        /usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000066fb0 sp=0xc000066f90 pc=0x55e334c8d886
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:342
runtime.forcegchelper()
        /usr/lib/golang/src/runtime/proc.go:276 +0xc5 fp=0xc000066fe0 sp=0xc000066fb0 pc=0x55e334c8d6e5
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000066fe8 sp=0xc000066fe0 pc=0x55e334cc0621
created by runtime.init.7
        /usr/lib/golang/src/runtime/proc.go:264 +0x37

goroutine 3 [GC sweep wait]:
runtime.gopark(0x55e335d5b260, 0x55e3364ebb40, 0x140c, 0x1)
        /usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc0000677a8 sp=0xc000067788 pc=0x55e334c8d886
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:342
runtime.bgsweep(0xc000036070)
        /usr/lib/golang/src/runtime/mgcsweep.go:163 +0xa5 fp=0xc0000677d8 sp=0xc0000677a8 pc=0x55e334c79485
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000677e0 sp=0xc0000677d8 pc=0x55e334cc0621
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:217 +0x5e

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x55e335d5b260, 0x55e3364ebea0, 0x140d, 0x1)
        /usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000067f78 sp=0xc000067f58 pc=0x55e334c8d886
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:342
runtime.bgscavenge(0xc000036070)
        /usr/lib/golang/src/runtime/mgcscavenge.go:265 +0xd6 fp=0xc000067fd8 sp=0xc000067f78 pc=0x55e334c774d6
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000067fe0 sp=0xc000067fd8 pc=0x55e334cc0621
created by runtime.gcenable
        /usr/lib/golang/src/runtime/mgc.go:218 +0x85

goroutine 5 [finalizer wait]:
runtime.gopark(0x55e335d5b260, 0x55e33651aa10, 0xffff1410, 0x1)
        /usr/lib/golang/src/runtime/proc.go:336 +0xe6 fp=0xc000066758 sp=0xc000066738 pc=0x55e334c8d886
runtime.goparkunlock(...)
        /usr/lib/golang/src/runtime/proc.go:342
runtime.runfinq()
        /usr/lib/golang/src/runtime/mfinal.go:175 +0xab fp=0xc0000667e0 sp=0xc000066758 pc=0x55e334c6e72b
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000667e8 sp=0xc0000667e0 pc=0x55e334cc0621
created by runtime.createfing
        /usr/lib/golang/src/runtime/mfinal.go:156 +0x66
fish: Job 1, 'aliyun --help' terminated by signal SIGABRT (Abort)
```

**Comment by JacksonTian** [comment]
Are you build the cli binary by yourself?

**Comment by eclipseo** [comment]
Yes It's fixed now. Meta was in wrong directory.  Sorry for the noise.
