### ISSUE TITLE
centos6 提示一个模块的版本不对。

### ISSUE THREAD

**Issue by doomzhou** [aliyun/aliyun-cli#8]
centos6 最小化安装　pip install aliyuncli 后运行报错如下

    Traceback (most recent call last):
    File "/usr/bin/aliyuncli", line 5, in <module>
        from pkg_resources import load_entry_point
    File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
        working_set.require(__requires__)
    File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
        needed = self.resolve(parse_requirements(requirements))
    File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: jmespath>=0.6.1,<=0.7.1

我通过
`sudo pip uninstall jmespath`

然后　
`sudo pip install jmespath==0.7.0`

然后可以用了。这是个坑。

**Comment by xiangxixids** [comment]
您好， 感谢上报这个bug，我们已经提交了更新，现在pip上已经修复了这个问题。欢迎有问题继续提出。

**Comment by doomzhou** [comment]
Traceback (most recent call last):
  File "/usr/bin/aliyuncli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: jmespath>=0.7.0,<=0.7.1

233
